workspace "Islandr" "WireGuard VPN management platform — C4 architecture model" {

    model {

        // ── Actors ────────────────────────────────────────────────────────
        admin   = person "Admin"    "Manages peers, users, roles, resources, and ACLs (Felix)."   "Admin"
        endUser = person "End User" "Manages own devices and views access list in plain language (Lena)." "User"

        // ── External systems ──────────────────────────────────────────────
        oidcProvider = softwareSystem "OIDC Provider"  "Authenticates users. Microsoft 365 or Google Workspace." "External"
        wireguard    = softwareSystem "WireGuard"      "Linux kernel VPN module. Managed via wg CLI." "External"
        nftables     = softwareSystem "nftables"       "Linux kernel packet filter. Enforces ACL rules generated by Islandr." "External"
        reverseProxy = softwareSystem "Cloudflare / Reverse Proxy"  "Edge & TLS termination. Cloudflare in front (default); a self-hosted reverse proxy (Caddy, nginx, Traefik) is an optional alternative." "External"

        // ── Islandr ───────────────────────────────────────────────────────
        islandr = softwareSystem "Islandr" "Self-hosted WireGuard management platform. Peer lifecycle, RBAC access control, nftables enforcement." {

            adminConsole = container "Admin Console" "Data-dense SPA for admins: peers, ACL matrix, users, roles, audit log, dashboard, settings." "Vue.js (ESM, no npm)" "SPA"

            selfServicePortal = container "Self-Service Portal" "Guided SPA for end users: enroll devices, view access list in plain language. German UI, informal Du." "Vue.js (ESM, no npm)" "SPA"

            backend = container "Islandr Backend" "REST API, domain logic, WireGuard and nftables adapters, OIDC token verification, activity polling, audit logging." "Quarkus 3 / Java 21 (native binary)" "Backend" {

                authPkg      = component "auth"      "Session management, local login, OIDC callback, admin bootstrap, session filter." "JAX-RS + CDI"
                identityPkg  = component "identity"  "OIDC provider registry, JWKS cache, ID token verification." "CDI"
                peerPkg      = component "peer"      "Peer lifecycle (create, enable, disable, delete), QR code generation, activity poller." "JAX-RS + CDI + @Scheduled"
                aclPkg       = component "acl"       "Sites, Resources, ResourcePorts, Roles, RoleResourceGrants. ACL matrix API." "JAX-RS + CDI"
                firewallPkg  = component "firewall"  "Full ruleset computation from ACL model, nft -c -f validation, atomic nft -f reload. Real/Mock/DryRun adapters." "CDI"
                wgPkg        = component "wg"        "WireGuard CLI adapter. Real/Mock/DryRun implementations selected via islandr.wg.mode config." "CDI"
                userPkg      = component "user"      "User management, avatar resolution (Gravatar → MS365 photo → deterministic initials)." "JAX-RS + CDI"
                auditPkg     = component "audit"     "Immutable append-only audit log. Written on every mutating action across all packages." "CDI"
                settingsPkg  = component "settings"  "Runtime instance settings (WG config, private key retention, OIDC providers). Stored in DB, audited." "JAX-RS + CDI"
                dashboardPkg = component "dashboard" "Dashboard aggregation: online peer count, audit summary, firewall status." "JAX-RS + CDI"
            }

            database = container "Database" "Persists peers, users, roles, resources, ACLs, audit log, activity samples, and runtime settings." "SQLite (default) or PostgreSQL" "Database"
        }

        // ── Context relationships ─────────────────────────────────────────
        admin    -> reverseProxy "Uses"          "HTTPS"
        endUser  -> reverseProxy "Uses"          "HTTPS"
        reverseProxy -> islandr  "Forwards to"   "HTTP"
        islandr  -> oidcProvider "Verifies ID tokens via OIDC / JWKS" "HTTPS"
        islandr  -> wireguard    "Configures peers" "wg CLI"
        islandr  -> nftables     "Generates and atomically reloads ACL ruleset" "nft CLI"

        // ── Container relationships ───────────────────────────────────────
        admin            -> adminConsole       "Uses"             "HTTPS via proxy"
        endUser          -> selfServicePortal  "Uses"             "HTTPS via proxy"
        reverseProxy     -> adminConsole       "Serves"           "HTTP (static files)"
        reverseProxy     -> selfServicePortal  "Serves"           "HTTP (static files)"
        reverseProxy     -> backend            "Proxies API"      "HTTP /api/v1"
        adminConsole     -> backend            "REST JSON"        "fetch /api/v1"
        selfServicePortal -> backend           "REST JSON"        "fetch /api/v1"
        backend          -> database           "Read/Write"       "JDBC / Hibernate ORM Panache"
        backend          -> oidcProvider       "Fetches JWKS, verifies ID tokens" "HTTPS"
        backend          -> wireguard          "wg set / wg show" "ProcessBuilder"
        backend          -> nftables           "nft -c -f / nft -f" "ProcessBuilder"

        // ── Component relationships ───────────────────────────────────────
        authPkg     -> identityPkg  "Delegates OIDC token verification"
        authPkg     -> userPkg      "Looks up or creates user on OIDC login"
        authPkg     -> auditPkg     "Logs login events"
        peerPkg     -> wgPkg        "Adds / removes peers from WireGuard interface"
        peerPkg     -> firewallPkg  "Triggers full ruleset recompute on peer state change"
        peerPkg     -> auditPkg     "Logs all peer mutations"
        aclPkg      -> firewallPkg  "Triggers full ruleset recompute on grant change"
        aclPkg      -> auditPkg     "Logs ACL mutations"
        userPkg     -> auditPkg     "Logs user mutations"
        settingsPkg -> auditPkg     "Logs settings changes"
        settingsPkg -> firewallPkg  "Triggers recompute on site-CIDR or resource change"
        firewallPkg -> nftables     "nft CLI calls"  "ProcessBuilder"
        wgPkg       -> wireguard    "wg CLI calls"   "ProcessBuilder"
        identityPkg -> oidcProvider "JWKS fetch"     "HTTPS"

        // ── Deployment ────────────────────────────────────────────────────
        production = deploymentEnvironment "Production" {
            deploymentNode "Internet" "" "Public network" {
                adminBrowser  = infrastructureNode "Admin Browser"     "" "Chrome / Firefox"
                userBrowser   = infrastructureNode "End User Browser"  "" "Chrome / Firefox"
                userWgClient  = infrastructureNode "WireGuard Client"  "" "WireGuard App (iOS/Android/macOS/Windows/Linux)"
            }
            deploymentNode "Hub VM" "Ubuntu 22.04+, public IP" "Linux" {
                deploymentNode "Linux Kernel" "" "" {
                    wgInterface     = infrastructureNode "wg0"      "WireGuard interface" "UDP 51820"
                    nftablesKernel  = infrastructureNode "nftables" "inet islandr table" "Packet filter"
                }
                deploymentNode "Reverse Proxy Process" "Optional — Cloudflare by default; Caddy / nginx / Traefik when self-hosted" "" {
                    proxyInstance = infrastructureNode "TLS Termination" "TCP 443 → 8080" ""
                }
                deploymentNode "Islandr Process" "Single native binary, runs as unprivileged user islandr" "" {
                    backendInstance = containerInstance backend
                    sqliteFile      = infrastructureNode "SQLite File" "/var/lib/islandr/islandr.db" "Durable file"
                }
            }
        }
    }

    views {

        // ── Static-site rendering (structurizr-site-generatr) ─────────────
        // Branding for the published interactive site at /architecture.
        // Ignored by the C4-PlantUML PNG export in docs.yml.
        properties {
            "generatr.site.exporter"          "structurizr"
            "generatr.site.theme"             "light"
            "plantuml.title"                  "false"
            "generatr.style.colors.primary"   "#0A1320"
            "generatr.style.colors.secondary" "#3BBBD2"
            "generatr.style.logoPath"         "site/logo.svg"
            "generatr.style.faviconPath"      "site/favicon.png"
            "generatr.style.customStylesheet" "site/custom.css"
        }

        systemContext islandr "SystemContext" "C4 Level 1 — System Context" {
            include *
            autoLayout lr
        }

        container islandr "Containers" "C4 Level 2 — Container View" {
            include *
            autoLayout lr
        }

        component backend "Components" "C4 Level 3 — Backend Components" {
            include *
            autoLayout lr
        }

        deployment * production "ProductionDeployment" "Deployment View — Hub VM" {
            include *
            autoLayout lr
        }

        styles {
            element "Person" {
                shape Person
                background #1168bd
                color #ffffff
                fontSize 14
            }
            element "Admin" {
                background #1168bd
            }
            element "User" {
                background #08427b
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #666666
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Component" {
                background #85bbf0
                color #000000
            }
            element "SPA" {
                shape WebBrowser
            }
            element "Backend" {
                shape RoundedBox
            }
            element "Database" {
                shape Cylinder
                background #438dd5
                color #ffffff
            }
            relationship "Relationship" {
                fontSize 11
            }
        }
    }
}
