workspace "Islandr" "WireGuard VPN management platform — C4 architecture model" {

    // Home page + roadmap for the published interactive site. Path is relative
    // to this DSL file and inside the site-generatr Docker mount (architecture/).
    !docs docs

    model {

        // ── Actors ────────────────────────────────────────────────────────
        admin   = person "Admin"    "Manages peers, users, roles, resources, and ACLs (Felix)."   "Admin"
        endUser = person "End User" "Manages own devices and views access list in plain language (Lena)." "User"

        // ── External systems ──────────────────────────────────────────────
        oidcProvider = softwareSystem "OIDC Provider"  "Authenticates users. Microsoft 365 or Google Workspace." "External"
        wireguard    = softwareSystem "WireGuard"      "Linux kernel VPN module. Managed via wg CLI." "External"
        nftables     = softwareSystem "nftables"       "Linux kernel packet filter. Enforces ACL rules generated by Islandr." "External"
        reverseProxy = softwareSystem "Cloudflare / Reverse Proxy"  "Edge & TLS termination. Cloudflare in front (default); a self-hosted reverse proxy (Caddy, nginx, Traefik) is an optional alternative." "External"
        resourceHost = softwareSystem "Resource Host" "A machine behind the VPN inside a site (e.g. an RDP server). For browser-based RDP the hub connects to it directly over TLS and relays to the browser." "External"

        // ── Islandr ───────────────────────────────────────────────────────
        islandr = softwareSystem "Islandr" "Self-hosted WireGuard management platform. Peer lifecycle, RBAC access control, nftables enforcement." {

            // Architecture Decision Records, rendered as this system's "Decisions"
            // section. Path is relative to this DSL file; gen-architecture.sh copies
            // docs/adr/ here transiently and rewrites the title lines to adr-tools
            // form (# N. Title) so the site-generatr importer accepts them.
            !decisions adr

            adminConsole = container "Admin Console" "Data-dense SPA for admins: peers, ACL matrix, users, roles, audit log, dashboard, settings." "Vue.js (ESM, no npm)" "SPA"

            selfServicePortal = container "Self-Service Portal" "Guided SPA for end users: enroll devices, view access list in plain language. German UI, informal Du." "Vue.js (ESM, no npm)" "SPA"

            backend = container "Islandr Backend" "REST API, domain logic, WireGuard and nftables adapters, OIDC token verification, activity polling, audit logging." "Quarkus 3 / Java 21 (native binary)" "Backend" {

                authPkg      = component "auth"      "Session management, local login (per-user PBKDF2 password or ENV admin), OIDC callback, admin bootstrap (seeds admin@local), session filter." "JAX-RS + CDI"
                identityPkg  = component "identity"  "OIDC provider registry, JWKS cache, ID token verification." "CDI"
                peerPkg      = component "peer"      "Peer lifecycle (create, enable, disable, delete), QR code generation, activity poller." "JAX-RS + CDI + @Scheduled"
                aclPkg       = component "acl"       "Sites, Resources, ResourcePorts, Roles, RoleResourceGrants, ACL matrix API. Browser-RDP WebSocket proxy (IronRDP RDCleanPath) with a per-port zero-trust grant check." "JAX-RS + CDI"
                firewallPkg  = component "firewall"  "Full ruleset computation from ACL model, nft -c -f validation, atomic nft -f reload. Real/Mock/DryRun adapters." "CDI"
                wgPkg        = component "wg"        "WireGuard CLI adapter. Real/Mock/DryRun implementations selected via islandr.wg.mode config." "CDI"
                userPkg      = component "user"      "User management, avatar resolution (Gravatar → MS365 photo → deterministic initials)." "JAX-RS + CDI"
                auditPkg     = component "audit"     "Immutable append-only audit log. Written on every mutating action across all packages." "CDI"
                settingsPkg  = component "settings"  "Runtime instance settings (WG config, private key retention, OIDC providers). Stored in DB, audited." "JAX-RS + CDI"
                dashboardPkg = component "dashboard" "Dashboard aggregation: online peer count, audit summary, firewall status." "JAX-RS + CDI"
            }

            database = container "Database" "Persists peers, users, roles, resources, ACLs, audit log, activity samples, and runtime settings." "SQLite (default) or PostgreSQL" "Database"
        }

        // ── Context relationships ─────────────────────────────────────────
        admin    -> reverseProxy "Uses"          "HTTPS"
        endUser  -> reverseProxy "Uses"          "HTTPS"
        reverseProxy -> islandr  "Forwards to"   "HTTP"
        islandr  -> oidcProvider "Verifies ID tokens via OIDC / JWKS" "HTTPS"
        islandr  -> wireguard    "Configures peers" "wg CLI"
        islandr  -> nftables     "Generates and atomically reloads ACL ruleset" "nft CLI"
        islandr  -> resourceHost "Proxies browser RDP over TLS (RDCleanPath)" "TCP/TLS"

        // ── Container relationships ───────────────────────────────────────
        admin            -> adminConsole       "Uses"             "HTTPS via proxy"
        endUser          -> selfServicePortal  "Uses"             "HTTPS via proxy"
        reverseProxy     -> adminConsole       "Serves"           "HTTP (static files)"
        reverseProxy     -> selfServicePortal  "Serves"           "HTTP (static files)"
        reverseProxy     -> backend            "Proxies API"      "HTTP /api/v1"
        adminConsole     -> backend            "REST JSON"        "fetch /api/v1"
        selfServicePortal -> backend           "REST JSON"        "fetch /api/v1"
        selfServicePortal -> backend           "Browser-RDP session (RDCleanPath)" "WebSocket"
        backend          -> database           "Read/Write"       "JDBC / Hibernate ORM Panache"
        backend          -> oidcProvider       "Fetches JWKS, verifies ID tokens" "HTTPS"
        backend          -> wireguard          "wg set / wg show" "ProcessBuilder"
        backend          -> nftables           "nft -c -f / nft -f" "ProcessBuilder"
        backend          -> resourceHost       "Browser-RDP: TCP connect + TLS relay" "TCP/TLS"

        // ── Component relationships ───────────────────────────────────────
        authPkg     -> identityPkg  "Delegates OIDC token verification"
        authPkg     -> userPkg      "Looks up or creates user on OIDC login"
        authPkg     -> auditPkg     "Logs login events"
        peerPkg     -> wgPkg        "Adds / removes peers from WireGuard interface"
        peerPkg     -> firewallPkg  "Triggers full ruleset recompute on peer state change"
        peerPkg     -> auditPkg     "Logs all peer mutations"
        aclPkg      -> firewallPkg  "Triggers full ruleset recompute on grant change"
        aclPkg      -> auditPkg     "Logs ACL mutations"
        aclPkg      -> resourceHost "Browser-RDP RDCleanPath proxy over TLS" "TCP/TLS"
        userPkg     -> auditPkg     "Logs user mutations"
        settingsPkg -> auditPkg     "Logs settings changes"
        settingsPkg -> firewallPkg  "Triggers recompute on site-CIDR or resource change"
        firewallPkg -> nftables     "nft CLI calls"  "ProcessBuilder"
        wgPkg       -> wireguard    "wg CLI calls"   "ProcessBuilder"
        identityPkg -> oidcProvider "JWKS fetch"     "HTTPS"

        // ── Deployment 1: native binary on the Hub VM (production) ─────────
        native = deploymentEnvironment "Native (systemd)" {
            deploymentNode "Internet" "" "Public network" {
                adminBrowser  = infrastructureNode "Admin Browser"     "" "Chrome / Firefox"
                userBrowser   = infrastructureNode "End User Browser"  "" "Chrome / Firefox"
                userWgClient  = infrastructureNode "WireGuard Client"  "" "WireGuard App (iOS/Android/macOS/Windows/Linux)"
            }
            deploymentNode "Hub VM" "Ubuntu 22.04+, public IP" "Linux" {
                deploymentNode "Linux Kernel" "" "" {
                    wgInterface     = infrastructureNode "wg0"      "WireGuard interface" "UDP 51820"
                    nftablesKernel  = infrastructureNode "nftables" "inet islandr table" "Packet filter"
                }
                deploymentNode "Reverse Proxy Process" "Optional — Cloudflare by default; Caddy / nginx / Traefik when self-hosted" "" {
                    proxyInstance = infrastructureNode "TLS Termination" "TCP 443 → 8080" ""
                }
                deploymentNode "systemd service" "islandr.service — single native binary, unprivileged user islandr, scoped sudo for wg/nft" "" {
                    nativeBackend = containerInstance backend
                    sqliteFile    = infrastructureNode "SQLite File" "/var/lib/islandr/islandr.db" "Durable file"
                }
            }
        }

        // ── Deployment 2: Docker (0.10.0 = evaluation only) ────────────────
        // The 0.10.0 image runs the mock wg/nft adapters: the full configuration
        // plane works and persists, but nothing is enforced on a host kernel.
        // Production Docker via the host-side socket proxy (ADR-0012) lands in
        // 0.11.0; there is no wg0 / nftables node here on purpose.
        docker = deploymentEnvironment "Docker (evaluation)" {
            deploymentNode "Internet" "" "Public network" {
                adminBrowserD = infrastructureNode "Admin Browser"     "" "Chrome / Firefox"
                userBrowserD  = infrastructureNode "End User Browser"  "" "Chrome / Firefox"
            }
            deploymentNode "Docker Host" "Any host with Docker (Linux / macOS)" "Docker" {
                deploymentNode "Reverse Proxy (optional)" "Cloudflare or self-hosted, in front of 8080" "" {
                    proxyInstanceD = infrastructureNode "TLS Termination" "TCP 443 → 8080" ""
                }
                deploymentNode "islandr container" "ghcr.io/chriscohnen/islandr:0.10.0 — demo/eval, mock wg + nft adapters (no host enforcement)" "Docker container" {
                    dockerBackend = containerInstance backend
                }
                dataVolume = infrastructureNode "Data volume" "islandr-data → /var/lib/islandr (SQLite)" "Docker volume"
            }
        }
    }

    views {

        // ── Static-site rendering (structurizr-site-generatr) ─────────────
        // Branding for the published interactive site at /architecture.
        // Ignored by the C4-PlantUML PNG export in docs.yml.
        properties {
            "generatr.site.exporter"          "structurizr"
            "generatr.site.theme"             "light"
            "plantuml.title"                  "false"
            "generatr.style.colors.primary"   "#0A1320"
            "generatr.style.colors.secondary" "#3BBBD2"
            "generatr.style.logoPath"         "site/logo.svg"
            "generatr.style.faviconPath"      "site/favicon.png"
            "generatr.style.customStylesheet" "site/custom.css"
        }

        systemContext islandr "SystemContext" "C4 Level 1 — System Context" {
            include *
            autoLayout lr
        }

        container islandr "Containers" "C4 Level 2 — Container View" {
            include *
            autoLayout lr
        }

        component backend "Components" "C4 Level 3 — Backend Components" {
            include *
            autoLayout lr
        }

        // Scope to the islandr system (not "*"): structurizr-site-generatr only
        // attaches a deployment view to a software system's navigation/page when the
        // view is scoped to that system. With "*" it renders the images but leaves an
        // empty redirect stub and no nav entry. The view key is unchanged, so the
        // C4-PlantUML PNG export for arc42 is unaffected.
        deployment islandr native "NativeDeployment" "Deployment View — native binary on the Hub VM (systemd)" {
            include *
            autoLayout lr
        }

        deployment islandr docker "DockerDeployment" "Deployment View — Docker container (evaluation, mock adapters)" {
            include *
            autoLayout lr
        }

        styles {
            element "Person" {
                shape Person
                background #1168bd
                color #ffffff
                fontSize 14
            }
            element "Admin" {
                background #1168bd
            }
            element "User" {
                background #08427b
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #666666
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Component" {
                background #85bbf0
                color #000000
            }
            element "SPA" {
                shape WebBrowser
            }
            element "Backend" {
                shape RoundedBox
            }
            element "Database" {
                shape Cylinder
                background #438dd5
                color #ffffff
            }
            relationship "Relationship" {
                fontSize 11
            }
        }
    }
}
