workspace "Islandr" "WireGuard VPN management platform — C4 architecture model" {

    // Home page + roadmap for the published interactive site. Path is relative
    // to this DSL file and inside the site-generatr Docker mount (architecture/).
    !docs docs

    model {

        // ── Actors ────────────────────────────────────────────────────────
        admin   = person "Admin"    "Manages peers, users, roles, resources, and ACLs (Felix)."   "Admin"
        endUser = person "End User" "Manages own devices and views access list in plain language (Lena)." "User"

        // ── External systems ──────────────────────────────────────────────
        oidcProvider = softwareSystem "OIDC Provider"  "Authenticates users. Microsoft 365 or Google Workspace." "External"
        wireguard    = softwareSystem "WireGuard"      "Linux kernel VPN module. Managed via wg CLI." "External"
        nftables     = softwareSystem "nftables"       "Linux kernel packet filter. Enforces ACL rules generated by Islandr." "External"
        reverseProxy = softwareSystem "Cloudflare / Reverse Proxy"  "Fully optional edge layer — Cloudflare, or a self-hosted reverse proxy (Caddy, nginx, Traefik). Islandr terminates TLS itself (dummy cert until an admin uploads one, hot-swapped at runtime) and can be reached directly with no proxy of any kind in front of it (ADR-0015)." "External"
        letsEncrypt  = softwareSystem "Let's Encrypt (ACME CA)" "Fully optional — only contacted when an admin sets a domain and enables ACME in Settings. Islandr's own hand-rolled RFC 8555 client requests, validates (HTTP-01), and renews a certificate directly; no certificate library, no external ACME client (ADR-0019)." "External"
        resourceHost = softwareSystem "Resource Host" "A machine behind the VPN inside a site (e.g. an RDP server). For browser-based RDP the hub connects to it directly over TLS and relays to the browser." "External"
        dnsUpstream  = softwareSystem "DNS Upstream" "Fully optional — only reached when the resource DNS resolver is enabled in Settings. Public or admin-configured recursive resolver(s) (default 1.1.1.1 / 8.8.8.8, Settings.dnsResolverUpstream) the hub forwards any query outside its own managed resource zone to, verbatim and unparsed (ADR-0023)." "External"

        // ── Islandr ───────────────────────────────────────────────────────
        islandr = softwareSystem "Islandr" "Self-hosted WireGuard management platform. Peer lifecycle, RBAC access control, nftables enforcement." {

            // Architecture Decision Records, rendered as this system's "Decisions"
            // section. Path is relative to this DSL file; gen-architecture.sh copies
            // docs/adr/ here transiently and rewrites the title lines to adr-tools
            // form (# N. Title) so the site-generatr importer accepts them.
            !decisions adr

            adminConsole = container "Admin Console" "Data-dense SPA for admins: peers, ACL matrix, users, roles, audit log, dashboard, settings." "Vue.js (ESM, no npm)" "SPA"

            selfServicePortal = container "Self-Service Portal" "Guided SPA for end users: enroll devices, view access list in plain language. German UI, informal Du." "Vue.js (ESM, no npm)" "SPA"

            backend = container "Islandr Backend" "REST API, domain logic, WireGuard and nftables adapters, OIDC token verification, activity polling, audit logging." "Quarkus 3 / Java 21 (native binary)" "Backend" {

                authPkg      = component "auth"      "Session management, local login (per-user PBKDF2 password or ENV admin), OIDC callback, admin bootstrap (seeds admin@local), session filter." "JAX-RS + CDI"
                identityPkg  = component "identity"  "OIDC provider registry, JWKS cache, ID token verification." "CDI"
                peerPkg      = component "peer"      "Peer lifecycle (create, enable, disable, delete), QR code generation, activity poller." "JAX-RS + CDI + @Scheduled"
                aclPkg       = component "acl"       "Sites, Resources, ResourcePorts, Roles, RoleResourceGrants, ACL matrix API. Browser-RDP WebSocket proxy (IronRDP RDCleanPath) with a per-port zero-trust grant check." "JAX-RS + CDI"
                firewallPkg  = component "firewall"  "Full ruleset computation from ACL model, nft -c -f validation, atomic nft -f reload. Real/Mock/DryRun adapters." "CDI"
                wgPkg        = component "wg"        "WireGuard CLI adapter. Real/Mock/DryRun implementations selected via islandr.wg.mode config." "CDI"
                userPkg      = component "user"      "User management, avatar resolution (Gravatar → MS365 photo → deterministic initials)." "JAX-RS + CDI"
                auditPkg     = component "audit"     "Immutable append-only audit log. Written on every mutating action across all packages." "CDI"
                settingsPkg  = component "settings"  "Runtime instance settings (WG config, private key retention, OIDC providers). Stored in DB, audited." "JAX-RS + CDI"
                dashboardPkg = component "dashboard" "Dashboard aggregation: online peer count, audit summary, firewall status." "JAX-RS + CDI"
                dnsPkg       = component "dns"       "Minimal DNS resolver (UDP/best-effort TCP :53), opt-in in Settings. Authoritative for the managed resource zone (Resource.dnsName), ACL-filtered answers (NXDOMAIN for resources the querying peer has no grant on); everything else forwarded upstream byte-for-byte, unparsed. Hand-rolled RFC 1035 wire format, no library (ADR-0023)." "CDI"
                tlsPkg       = component "tls"       "TLS keystore management. Hot-swaps between dummy self-signed cert and an admin-uploaded or ACME-issued cert at runtime, no restart (ADR-0015)." "CDI"
                acmePkg      = component "acme"      "Hand-rolled RFC 8555 ACME client. Requests, validates (HTTP-01 or DNS-01 manual mode), and renews a certificate when ACME is enabled in Settings; no certificate library (ADR-0019, ADR-0020)." "JAX-RS + CDI + @Scheduled"
                proxyPkg     = component "proxy"     "Host-side Unix-socket-proxy channel for wg/nft when the backend runs unprivileged in a container. Adapter-mode resolution (explicit > container-detected > mock), degraded 'enforcement unavailable' status (ADR-0012)." "CDI"
                discoveryPkg = component "discovery" "Admin-triggered device discovery: enumerates a site's CIDR, probes host liveness with unprivileged sockets, fingerprints a resource type from open ports, bulk-imports the reviewed selection as Resource rows (ADR-0014)." "JAX-RS + CDI"
                adminPkg     = component "admin"     "Instance config export/import, seeded-data timestamp repair on import, version/update-check endpoint." "JAX-RS + CDI"
            }

            database = container "Database" "Persists peers, users, roles, resources, ACLs, audit log, activity samples, and runtime settings." "SQLite (default) or PostgreSQL" "Database"
        }

        // ── Context relationships ─────────────────────────────────────────
        // Two valid paths, not one mandatory hop: the reverse proxy is
        // entirely optional (ADR-0015) since Islandr terminates TLS itself.
        admin    -> islandr     "Uses directly (built-in TLS)"       "HTTPS"
        endUser  -> islandr     "Uses directly (built-in TLS)"       "HTTPS"
        admin    -> reverseProxy "Uses (optional path)"              "HTTPS"
        endUser  -> reverseProxy "Uses (optional path)"              "HTTPS"
        reverseProxy -> islandr  "Forwards to (optional layer)"      "HTTP or HTTPS"
        islandr  -> oidcProvider "Verifies ID tokens via OIDC / JWKS" "HTTPS"
        islandr  -> wireguard    "Configures peers" "wg CLI"
        islandr  -> nftables     "Generates and atomically reloads ACL ruleset" "nft CLI"
        islandr  -> letsEncrypt  "Requests, validates (HTTP-01), and renews a certificate (optional, ACME mode only)" "HTTPS"
        letsEncrypt -> islandr   "Validates domain control via HTTP-01 challenge callback" "HTTP"
        islandr  -> resourceHost "Proxies browser RDP over TLS (RDCleanPath)" "TCP/TLS"
        islandr  -> dnsUpstream  "Forwards non-zone DNS queries verbatim (optional, resolver enabled only)" "UDP/TCP 53"

        // ── Container relationships ───────────────────────────────────────
        // Same "two valid paths" shape as the context view: the backend
        // serves the SPAs and the API directly over its own built-in TLS;
        // the reverse proxy, when present, is an optional layer in front.
        admin            -> adminConsole       "Uses directly (built-in TLS)"  "HTTPS"
        endUser          -> selfServicePortal  "Uses directly (built-in TLS)"  "HTTPS"
        admin            -> adminConsole       "Uses (optional path)"          "HTTPS via proxy"
        endUser          -> selfServicePortal  "Uses (optional path)"          "HTTPS via proxy"
        backend          -> adminConsole       "Serves directly"               "HTTP/HTTPS (static files)"
        backend          -> selfServicePortal  "Serves directly"               "HTTP/HTTPS (static files)"
        reverseProxy     -> adminConsole       "Serves (optional layer)"       "HTTP (static files)"
        reverseProxy     -> selfServicePortal  "Serves (optional layer)"       "HTTP (static files)"
        reverseProxy     -> backend            "Proxies API (optional layer)"  "HTTP /api/v1"
        adminConsole     -> backend            "REST JSON"        "fetch /api/v1"
        selfServicePortal -> backend           "REST JSON"        "fetch /api/v1"
        selfServicePortal -> backend           "Browser-RDP session (RDCleanPath)" "WebSocket"
        backend          -> database           "Read/Write"       "JDBC / Hibernate ORM Panache"
        backend          -> oidcProvider       "Fetches JWKS, verifies ID tokens" "HTTPS"
        backend          -> wireguard          "wg set / wg show" "ProcessBuilder"
        backend          -> nftables           "nft -c -f / nft -f" "ProcessBuilder"
        backend          -> letsEncrypt        "ACME directory, order, and challenge requests (optional, ACME mode only)" "HTTPS"
        letsEncrypt      -> backend            "HTTP-01 challenge callback" "HTTP"
        backend          -> resourceHost       "Browser-RDP: TCP connect + TLS relay" "TCP/TLS"
        backend          -> dnsUpstream        "Forwards non-zone DNS queries verbatim (optional, resolver enabled only)" "UDP/TCP 53"

        // ── Component relationships ───────────────────────────────────────
        authPkg     -> identityPkg  "Delegates OIDC token verification"
        authPkg     -> userPkg      "Looks up or creates user on OIDC login"
        authPkg     -> auditPkg     "Logs login events"
        peerPkg     -> wgPkg        "Adds / removes peers from WireGuard interface"
        peerPkg     -> firewallPkg  "Triggers full ruleset recompute on peer state change"
        peerPkg     -> auditPkg     "Logs all peer mutations"
        aclPkg      -> firewallPkg  "Triggers full ruleset recompute on grant change"
        aclPkg      -> auditPkg     "Logs ACL mutations"
        aclPkg      -> resourceHost "Browser-RDP RDCleanPath proxy over TLS" "TCP/TLS"
        userPkg     -> auditPkg     "Logs user mutations"
        settingsPkg -> auditPkg     "Logs settings changes"
        settingsPkg -> firewallPkg  "Triggers recompute on site-CIDR or resource change"
        settingsPkg -> tlsPkg       "Uploads/replaces certificate PEM, reads certificate info"
        firewallPkg -> nftables     "nft CLI calls"  "ProcessBuilder"
        firewallPkg -> proxyPkg     "Delegates nft calls when containerized (socket mode)" "islandr.nft.mode=socket"
        wgPkg       -> wireguard    "wg CLI calls"   "ProcessBuilder"
        wgPkg       -> proxyPkg     "Delegates wg calls when containerized (socket mode)" "islandr.wg.mode=socket"
        proxyPkg    -> auditPkg     "Logs enforcement mode changes"
        identityPkg -> oidcProvider "JWKS fetch"     "HTTPS"
        dnsPkg      -> aclPkg       "ACL-scoped grant check for filtered zone answers" "AclService.hasAnyGrant"
        dnsPkg      -> dnsUpstream  "Forwards non-zone queries verbatim" "UDP/TCP 53"
        acmePkg     -> letsEncrypt  "ACME directory, order, and HTTP-01/DNS-01 challenge requests" "HTTPS"
        letsEncrypt -> acmePkg      "HTTP-01 challenge callback" "HTTP"
        acmePkg     -> tlsPkg       "Installs renewed certificate into the keystore"
        acmePkg     -> auditPkg     "Logs renewal attempts and outcomes"
        discoveryPkg -> resourceHost "Unprivileged liveness/port probes over the existing WireGuard route" "TCP/UDP"
        discoveryPkg -> aclPkg      "Bulk-imports reviewed hosts as Resource rows"
        adminPkg    -> auditPkg     "Logs config import/export"

        // ── Deployment 1: native binary on the Hub VM (production) ─────────
        native = deploymentEnvironment "Native (systemd)" {
            deploymentNode "Internet" "" "Public network" {
                adminBrowser  = infrastructureNode "Admin Browser"     "" "Chrome / Firefox"
                userBrowser   = infrastructureNode "End User Browser"  "" "Chrome / Firefox"
                userWgClient  = infrastructureNode "WireGuard Client"  "" "WireGuard App (iOS/Android/macOS/Windows/Linux)"
            }
            deploymentNode "Hub VM" "Ubuntu 22.04+, public IP" "Linux" {
                deploymentNode "Linux Kernel" "" "" {
                    wgInterface     = infrastructureNode "wg0"      "WireGuard interface" "UDP 51820"
                    nftablesKernel  = infrastructureNode "nftables" "inet islandr table" "Packet filter"
                }
                deploymentNode "Reverse Proxy Process" "Fully optional — Cloudflare by default when used; Caddy / nginx / Traefik when self-hosted" "" {
                    proxyInstance = infrastructureNode "TLS Termination" "TCP 443 → 8080/8443" ""
                }
                deploymentNode "systemd service" "islandr.service — single native binary, unprivileged user islandr, scoped sudo for wg/nft" "" {
                    nativeBackend = containerInstance backend
                    builtinTls    = infrastructureNode "Built-in TLS" "HTTPS :8443 — dummy cert until an admin uploads one, hot-swapped at runtime, no proxy required (ADR-0015)" "Quarkus TLS registry"
                    dnsResolverInfra = infrastructureNode "DNS Resolver" "UDP/TCP :53, opt-in in Settings — needs CAP_NET_BIND_SERVICE (outside ADR-0011's sudoers scope); bind failure is caught and logged, resolver stays off rather than crashing (ADR-0023)" ""
                    sqliteFile    = infrastructureNode "SQLite File" "/var/lib/islandr/islandr.db" "Durable file"
                }
            }
        }

        // ── Deployment 2: Docker (production-capable via socket proxy, ADR-0012) ──
        // A bare `docker run`/compose boots the full GUI unprivileged: config is
        // saved but enforcement is degraded ("enforcement unavailable", mock-like)
        // until the host-side islandr-proxy is attached. Attaching it (this view)
        // makes wg/nft calls real without granting the container NET_ADMIN,
        // --network host, or the Docker socket — see ADR-0012.
        docker = deploymentEnvironment "Docker (host socket proxy)" {
            deploymentNode "Internet" "" "Public network" {
                adminBrowserD = infrastructureNode "Admin Browser"     "" "Chrome / Firefox"
                userBrowserD  = infrastructureNode "End User Browser"  "" "Chrome / Firefox"
            }
            deploymentNode "Docker Host" "Linux host with Docker + wg + nft installed" "Docker" {
                deploymentNode "Linux Kernel" "" "" {
                    wgInterfaceD    = infrastructureNode "wg0"      "WireGuard interface" "UDP 51820"
                    nftablesKernelD = infrastructureNode "nftables" "inet islandr table" "Packet filter"
                }
                deploymentNode "Reverse Proxy (fully optional)" "Cloudflare or self-hosted, in front of 8080/8443 — the container terminates TLS itself, see Built-in TLS below" "" {
                    proxyInstanceD = infrastructureNode "TLS Termination" "TCP 443 → 8080/8443" ""
                }
                islandrProxy = infrastructureNode "islandr-proxy.service" "systemd service, unprivileged user, socket-activated on /run/islandr/proxy.sock, scoped sudoers for wg/nft — allowlisted JSON protocol (ADR-0012)" ""
                deploymentNode "islandr container" "ghcr.io/chriscohnen/islandr:latest — ISLANDR_WG_MODE=socket, ISLANDR_NFT_MODE=socket" "Docker container" {
                    dockerBackend = containerInstance backend
                    builtinTlsD   = infrastructureNode "Built-in TLS" "HTTPS :8443 — dummy cert until an admin uploads one, no proxy required (ADR-0015)" "Quarkus TLS registry"
                }
                dataVolume = infrastructureNode "Data volume" "islandr-data → /var/lib/islandr (SQLite)" "Docker volume"
            }
        }
    }

    views {

        // ── Static-site rendering (structurizr-site-generatr) ─────────────
        // Branding for the published interactive site at /architecture.
        // Ignored by the C4-PlantUML PNG export in docs.yml.
        properties {
            "generatr.site.exporter"          "structurizr"
            "generatr.site.theme"             "light"
            "plantuml.title"                  "false"
            "generatr.style.colors.primary"   "#0A1320"
            "generatr.style.colors.secondary" "#3BBBD2"
            "generatr.style.logoPath"         "site/logo.svg"
            "generatr.style.faviconPath"      "site/favicon.png"
            "generatr.style.customStylesheet" "site/custom.css"
        }

        systemContext islandr "SystemContext" "C4 Level 1 — System Context" {
            include *
            autoLayout lr
        }

        container islandr "Containers" "C4 Level 2 — Container View" {
            include *
            autoLayout lr
        }

        component backend "Components" "C4 Level 3 — Backend Components" {
            include *
            autoLayout lr
        }

        // Scope to the islandr system (not "*"): structurizr-site-generatr only
        // attaches a deployment view to a software system's navigation/page when the
        // view is scoped to that system. With "*" it renders the images but leaves an
        // empty redirect stub and no nav entry. The view key is unchanged, so the
        // C4-PlantUML PNG export for arc42 is unaffected.
        deployment islandr native "NativeDeployment" "Deployment View — native binary on the Hub VM (systemd)" {
            include *
            autoLayout lr
        }

        deployment islandr docker "DockerDeployment" "Deployment View — Docker container (evaluation, mock adapters)" {
            include *
            autoLayout lr
        }

        styles {
            element "Person" {
                shape Person
                background #1168bd
                color #ffffff
                fontSize 14
            }
            element "Admin" {
                background #1168bd
            }
            element "User" {
                background #08427b
            }
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "External" {
                background #666666
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "Component" {
                background #85bbf0
                color #000000
            }
            element "SPA" {
                shape WebBrowser
            }
            element "Backend" {
                shape RoundedBox
            }
            element "Database" {
                shape Cylinder
                background #438dd5
                color #ffffff
            }
            relationship "Relationship" {
                fontSize 11
            }
        }
    }
}
