package de.chriscohnen.islandr.firewall;

import de.chriscohnen.islandr.acl.Resource;
import de.chriscohnen.islandr.acl.ResourcePort;
import de.chriscohnen.islandr.acl.Role;
import de.chriscohnen.islandr.acl.RoleResourceGrant;
import de.chriscohnen.islandr.acl.RoleResourceTypeGrant;
import de.chriscohnen.islandr.acl.UserResourceGrant;
import de.chriscohnen.islandr.peer.Peer;
import de.chriscohnen.islandr.user.User;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Generates the {@code inet islandr} nftables ruleset from the current DB state.
 * Pure read-only — no entity is touched, no transaction is opened for write.
 * The caller (RulesetService) is responsible for handing the output to the adapter.
 *
 * <p>Dual-stack: for each peer, rules are emitted for every assigned IP (IPv4 and/or IPv6)
 * against resources of the same address family. Cross-family pairs are silently skipped.
 *
 * <p>Output shape (ADR-0003 §F-08, ADR-0006 §F-08a):
 * <pre>
 * # banner — DO NOT EDIT, regenerated by Islandr on every ACL change
 * flush table inet islandr
 * table inet islandr {
 *   chain forward {
 *     type filter hook forward priority 0; policy drop;
 *     iifname != "wg0" oifname != "wg0" accept comment "islandr:not-wg-traffic, leave to host"
 *     ct state established,related accept comment "islandr:conntrack return traffic"
 *     ct state invalid drop comment "islandr:conntrack invalid"
 *
 *     # IPv4 accept rule
 *     iifname "wg0" ip saddr 10.8.0.5 ip daddr 10.20.0.5 tcp dport 3389 accept comment "..."
 *     # IPv6 accept rule
 *     iifname "wg0" ip6 saddr fd11::5 ip6 daddr fd11::50 tcp dport 3389 accept comment "..."
 *   }
 * }
 * </pre>
 */
@ApplicationScoped
public class RuleBuilder {

    static final String BANNER = String.join("\n",
            "#",
            "# This nftables ruleset is generated by Islandr from the database",
            "# (table `inet islandr`). It is rewritten on every ACL change.",
            "# Do NOT edit by hand — your changes will be lost at the next apply.",
            "# Other tables on this system are not touched by Islandr.",
            "#"
    );

    @ConfigProperty(name = "islandr.wg.interface") String wgInterface;

    @PersistenceContext EntityManager em;

    public Snapshot build() {
        List<Peer> peers = Peer.<Peer>list("enabled", true);
        if (peers.isEmpty()) {
            return new Snapshot(emptyTable(), 0);
        }

        Map<String, String> userName = new HashMap<>();
        for (User u : User.<User>list("id in ?1",
                peers.stream().map(p -> p.userId).distinct().toList())) {
            userName.put(u.id, u.name);
        }

        Map<String, List<String>> rolesByUser = new HashMap<>();
        @SuppressWarnings("unchecked")
        List<Object[]> userRoleRows = em.createNativeQuery(
                        "SELECT user_id, role_id FROM user_roles")
                .getResultList();
        for (Object[] row : userRoleRows) {
            rolesByUser.computeIfAbsent((String) row[0], k -> new ArrayList<>())
                    .add((String) row[1]);
        }

        Map<String, Role> roleById = new HashMap<>();
        for (Role r : Role.<Role>listAll()) roleById.put(r.id, r);
        // Auto-membership roles (Everyone) apply to every user-linked peer (ADR-0013).
        List<String> autoAllRoleIds = roleById.values().stream()
                .filter(r -> r.autoAll).map(r -> r.id).toList();
        Map<String, List<RoleResourceGrant>> grantsByRole = new HashMap<>();
        for (RoleResourceGrant g : RoleResourceGrant.<RoleResourceGrant>listAll()) {
            grantsByRole.computeIfAbsent(g.roleId, k -> new ArrayList<>()).add(g);
        }

        Map<String, Resource> resourceById = new HashMap<>();
        for (Resource r : Resource.<Resource>listAll()) resourceById.put(r.id, r);

        // Type grants ("all printers in Homeoffice", ACL type-grants
        // 2026-07-28): expand each into a synthetic all-ports RoleResourceGrant
        // per matching resource — never persisted, just reuses the exact same
        // grant shape everything below this point already knows how to render,
        // so the rest of RuleBuilder needs no further changes. Additive only:
        // these are appended alongside, never replacing, concrete grants.
        for (RoleResourceTypeGrant tg : RoleResourceTypeGrant.<RoleResourceTypeGrant>listAll()) {
            for (Resource r : resourceById.values()) {
                if (r.siteId.equals(tg.siteId) && r.type.equals(tg.resourceType)) {
                    grantsByRole.computeIfAbsent(tg.roleId, k -> new ArrayList<>())
                            .add(RoleResourceGrant.createNew(tg.roleId, r.id, true));
                }
            }
        }
        Map<String, List<ResourcePort>> portsByResource = new HashMap<>();
        for (ResourcePort p : ResourcePort.<ResourcePort>listAll()) {
            portsByResource.computeIfAbsent(p.resourceId, k -> new ArrayList<>()).add(p);
        }
        Map<String, Set<String>> portsByGrant = new HashMap<>();
        @SuppressWarnings("unchecked")
        List<Object[]> grantPortRows = em.createNativeQuery(
                        "SELECT grant_id, port_id FROM role_resource_grant_ports")
                .getResultList();
        for (Object[] row : grantPortRows) {
            portsByGrant.computeIfAbsent((String) row[0], k -> new HashSet<>())
                    .add((String) row[1]);
        }

        Map<String, List<UserResourceGrant>> grantsByUser = new HashMap<>();
        for (UserResourceGrant g : UserResourceGrant.<UserResourceGrant>listAll()) {
            grantsByUser.computeIfAbsent(g.userId, k -> new ArrayList<>()).add(g);
        }
        Map<String, Set<String>> portsByUserGrant = new HashMap<>();
        @SuppressWarnings("unchecked")
        List<Object[]> userGrantPortRows = em.createNativeQuery(
                        "SELECT grant_id, port_id FROM user_resource_grant_ports")
                .getResultList();
        for (Object[] row : userGrantPortRows) {
            portsByUserGrant.computeIfAbsent((String) row[0], k -> new HashSet<>())
                    .add((String) row[1]);
        }

        Map<String, String> rulesByKey = new LinkedHashMap<>();
        // (peerIp, resource.ip) pairs with at least one grant — for implicit ICMP
        Set<String> icmpPairs = new HashSet<>();

        for (Peer peer : peers) {
            List<String> userRoles = new ArrayList<>(rolesByUser.getOrDefault(peer.userId, List.of()));
            // Everyone (auto_all) reaches every user-linked peer, present or future.
            // Site/gateway peers (userId=null) are routing, not users — excluded.
            if (peer.userId != null) userRoles.addAll(autoAllRoleIds);
            List<UserResourceGrant> directGrants = grantsByUser.getOrDefault(peer.userId, List.of());
            // A direct user-grant (ADR-0024) must render even for a user with
            // zero roles — role membership and direct grants are independent
            // sources, so only skip the peer when both are empty.
            if (userRoles.isEmpty() && directGrants.isEmpty()) continue;

            // Collect all assigned IPs for this peer (IPv4 always present; IPv6 optional)
            List<String> peerIps = peerIpsOf(peer);

            for (String roleId : userRoles) {
                Role role = roleById.get(roleId);
                if (role == null) continue;
                for (RoleResourceGrant g : grantsByRole.getOrDefault(roleId, List.of())) {
                    Set<String> grantedPortIds = g.allPorts ? Set.of() : portsByGrant.getOrDefault(g.id, Set.of());
                    emitRulesForGrant(peer, peerIps, g.resourceId, g.allPorts, grantedPortIds,
                            escape(role.name), resourceById, portsByResource, userName, rulesByKey, icmpPairs);
                }
            }

            // Direct user grants (ADR-0024) — independent of role membership
            // entirely, so a user with zero roles (a defensive edge case;
            // auto_all "Everyone" is normally always present per ADR-0013)
            // still gets their direct grants rendered.
            for (UserResourceGrant g : directGrants) {
                Set<String> grantedPortIds = g.allPorts ? Set.of() : portsByUserGrant.getOrDefault(g.id, Set.of());
                emitRulesForGrant(peer, peerIps, g.resourceId, g.allPorts, grantedPortIds,
                        "(direct)", resourceById, portsByResource, userName, rulesByKey, icmpPairs);
            }
        }

        // Implicit ICMP/ICMPv6 accept for every (peerIp, resIp) pair with at least one port grant
        for (String pair : icmpPairs) {
            String[] parts = pair.split("\\|", 4);
            String peerIp = parts[0], resIp = parts[1], peerName = parts[2], resName = parts[3];
            String icmpKey = peerIp + "|" + resIp + "|icmp";
            if (rulesByKey.containsKey(icmpKey)) continue;
            String family   = isV6(peerIp) ? "ip6" : "ip";
            String icmpType = isV6(peerIp) ? "icmpv6 type echo-request" : "icmp type echo-request";
            String rule = String.format(
                    "    iifname \"%s\" %s saddr %s %s daddr %s %s accept comment \"%s\"",
                    wgInterface, family, peerIp, family, resIp, icmpType,
                    "islandr:peer=" + peerName + " resource=" + resName + " ping");
            rulesByKey.put(icmpKey, rule);
        }

        StringBuilder sb = new StringBuilder(BANNER.length() + 256 + 96 * rulesByKey.size());
        sb.append(BANNER).append('\n');
        sb.append("add table inet islandr\n");
        sb.append("flush table inet islandr\n");
        sb.append("table inet islandr {\n");
        sb.append("  chain forward {\n");
        sb.append("    type filter hook forward priority -1; policy drop;\n");
        sb.append('\n');
        sb.append(String.format(
                "    iifname != \"%s\" oifname != \"%s\" accept comment \"islandr:not-wg-traffic, leave to host\"\n",
                wgInterface, wgInterface));
        sb.append("    ct state established,related accept comment \"islandr:conntrack return traffic\"\n");
        sb.append("    ct state invalid drop comment \"islandr:conntrack invalid\"\n");
        if (!rulesByKey.isEmpty()) {
            sb.append('\n');
            for (String rule : rulesByKey.values()) {
                sb.append(rule).append('\n');
            }
        }
        sb.append("  }\n");
        sb.append("}\n");

        return new Snapshot(sb.toString(), rulesByKey.size());
    }

    /**
     * Renders one grant (role-derived or direct-user, ADR-0024) into allow
     * rules for one peer — the single place a (peer, resource, ports) triple
     * becomes rule text, called once per role-grant and once per direct
     * user-grant so both sources stay byte-for-byte consistent.
     */
    private void emitRulesForGrant(
            Peer peer, List<String> peerIps, String resourceId, boolean allPorts,
            Set<String> grantedPortIds, String roleLabel,
            Map<String, Resource> resourceById, Map<String, List<ResourcePort>> portsByResource,
            Map<String, String> userName, Map<String, String> rulesByKey, Set<String> icmpPairs) {
        Resource res = resourceById.get(resourceId);
        if (res == null) return;
        List<ResourcePort> resPorts = portsByResource.getOrDefault(res.id, List.of());
        if (resPorts.isEmpty()) return;
        List<ResourcePort> grantedPorts = allPorts
                ? resPorts
                : resPorts.stream().filter(rp -> grantedPortIds.contains(rp.id)).toList();

        for (String peerIp : peerIps) {
            if (isV6(peerIp) != isV6(res.ip)) continue;

            String family   = isV6(peerIp) ? "ip6" : "ip";
            String peerName = escape(peer.name);
            String uName    = escape(userName.getOrDefault(peer.userId, "?"));

            for (ResourcePort rp : grantedPorts) {
                if ("web-only".equals(rp.rdpAccessMode)) continue;
                String comment = String.format(
                        "islandr:role=%s peer=%s user=%s resource=%s %s%s",
                        roleLabel, peerName, uName,
                        escape(res.name), escape(rp.protocol),
                        rp.label == null || rp.label.isBlank() ? "" : " " + escape(rp.label));
                for (String[] td : expandTransport(rp)) {
                    String effectiveTransport = td[0];
                    String dportClause = td[1];
                    String key = peerIp + "|" + res.ip + "|"
                            + effectiveTransport + "|" + rp.port + "|"
                            + (rp.portEnd == null ? "" : rp.portEnd);
                    if (rulesByKey.containsKey(key)) continue;
                    String rule = dportClause.isEmpty()
                            ? String.format(
                                    "    iifname \"%s\" %s saddr %s %s daddr %s %s accept comment \"%s\"",
                                    wgInterface, family, peerIp, family, res.ip, effectiveTransport, comment)
                            : String.format(
                                    "    iifname \"%s\" %s saddr %s %s daddr %s %s %s accept comment \"%s\"",
                                    wgInterface, family, peerIp, family, res.ip, effectiveTransport, dportClause, comment);
                    rulesByKey.put(key, rule);
                }
                icmpPairs.add(peerIp + "|" + res.ip + "|" + peerName + "|" + escape(res.name));
            }
        }
    }

    private String emptyTable() {
        return BANNER + "\n"
                + "add table inet islandr\n"
                + "flush table inet islandr\n"
                + "table inet islandr {\n"
                + "  chain forward {\n"
                + "    type filter hook forward priority -1; policy drop;\n"
                + "\n"
                + String.format(
                        "    iifname != \"%s\" oifname != \"%s\" accept comment \"islandr:not-wg-traffic, leave to host\"\n",
                        wgInterface, wgInterface)
                + "    ct state established,related accept comment \"islandr:conntrack return traffic\"\n"
                + "    ct state invalid drop comment \"islandr:conntrack invalid\"\n"
                + "  }\n"
                + "}\n";
    }

    /** All assigned IPs for a peer: IPv4 always first (if present), IPv6 second (if present). */
    private static List<String> peerIpsOf(Peer peer) {
        List<String> ips = new ArrayList<>(2);
        if (peer.assignedIp != null && !peer.assignedIp.isBlank()) ips.add(peer.assignedIp);
        if (peer.assignedIpv6 != null && !peer.assignedIpv6.isBlank()) ips.add(peer.assignedIpv6);
        return ips;
    }

    private static boolean isV6(String ip) {
        return ip != null && ip.contains(":");
    }

    private static List<String[]> expandTransport(ResourcePort rp) {
        String dport;
        if (rp.port == 0) {
            dport = "";
        } else if (rp.portEnd != null) {
            dport = "dport " + rp.port + "-" + rp.portEnd;
        } else {
            dport = "dport " + rp.port;
        }
        if ("both".equals(rp.transport)) {
            return java.util.Arrays.asList(new String[]{"tcp", dport}, new String[]{"udp", dport});
        }
        return java.util.Collections.singletonList(new String[]{rp.transport, dport});
    }

    private static String escape(String s) {
        if (s == null) return "";
        return s.replace("\"", "").replace("\\", "").replace("\n", " ");
    }

    public record Snapshot(String rulesetText, int ruleCount) {}
}
