package de.chriscohnen.islandr.firewall;

import de.chriscohnen.islandr.acl.Resource;
import de.chriscohnen.islandr.acl.ResourcePort;
import de.chriscohnen.islandr.acl.Role;
import de.chriscohnen.islandr.acl.RoleResourceGrant;
import de.chriscohnen.islandr.peer.Peer;
import de.chriscohnen.islandr.user.User;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Generates the {@code inet islandr} nftables ruleset from the current DB
 * state. Pure read-only — no entity is touched, no transaction is opened
 * for write. The caller (RulesetService) is responsible for handing the
 * output to the adapter.
 *
 * <p>Output shape (ADR-0003 §F-08, ADR-0006 §F-08a):
 * <pre>
 * # banner — DO NOT EDIT, regenerated by Islandr on every ACL change
 * flush table inet islandr
 * table inet islandr {
 *   chain forward {
 *     type filter hook forward priority 0; policy drop;
 *
 *     # Per (peer, resource, transport, port) accept rule with comment.
 *     iifname "wg0" ip saddr 10.8.0.5 ip daddr 10.20.0.5 tcp dport 3389 \
 *         accept comment "islandr:role=Vertrieb peer=macbook-felix resource=Terminal-01 RDP"
 *   }
 * }
 * </pre>
 *
 * The {@code flush table inet islandr} at the top makes the apply atomic on
 * just that table — other tables ({@code inet filter} for SSH etc.) are
 * untouched.
 */
@ApplicationScoped
public class RuleBuilder {

    /** Big banner the generator always emits at the top of the ruleset. */
    static final String BANNER = String.join("\n",
            "#",
            "# This nftables ruleset is generated by Islandr from the database",
            "# (table `inet islandr`). It is rewritten on every ACL change.",
            "# Do NOT edit by hand — your changes will be lost at the next apply.",
            "# Other tables on this system are not touched by Islandr.",
            "#"
    );

    @ConfigProperty(name = "islandr.wg.interface") String wgInterface;

    @PersistenceContext EntityManager em;

    /**
     * Build the full ruleset string from the current DB snapshot. The
     * returned text is what the adapter writes to a temp file and feeds to
     * {@code nft -c -f}.
     */
    public Snapshot build() {
        // Snapshot all the rows we need in one pass each, to avoid lazy
        // loading and N+1 inside the rule loop.
        List<Peer> peers = Peer.<Peer>list("enabled", true);
        if (peers.isEmpty()) {
            return new Snapshot(emptyTable(), 0);
        }

        // peer.userId → user.name for the comment
        Map<String, String> userName = new HashMap<>();
        for (User u : User.<User>list("id in ?1",
                peers.stream().map(p -> p.userId).distinct().toList())) {
            userName.put(u.id, u.name);
        }

        // Roles each user belongs to (one query, then group in memory)
        Map<String, List<String>> rolesByUser = new HashMap<>();
        @SuppressWarnings("unchecked")
        List<Object[]> userRoleRows = em.createNativeQuery(
                        "SELECT user_id, role_id FROM user_roles")
                .getResultList();
        for (Object[] row : userRoleRows) {
            rolesByUser.computeIfAbsent((String) row[0], k -> new ArrayList<>())
                    .add((String) row[1]);
        }

        // role.id → role.name (for the comment) + grants of that role.
        Map<String, Role> roleById = new HashMap<>();
        for (Role r : Role.<Role>listAll()) roleById.put(r.id, r);
        Map<String, List<RoleResourceGrant>> grantsByRole = new HashMap<>();
        for (RoleResourceGrant g : RoleResourceGrant.<RoleResourceGrant>listAll()) {
            grantsByRole.computeIfAbsent(g.roleId, k -> new ArrayList<>()).add(g);
        }

        // Resources + ports lookup
        Map<String, Resource> resourceById = new HashMap<>();
        for (Resource r : Resource.<Resource>listAll()) resourceById.put(r.id, r);
        Map<String, List<ResourcePort>> portsByResource = new HashMap<>();
        for (ResourcePort p : ResourcePort.<ResourcePort>listAll()) {
            portsByResource.computeIfAbsent(p.resourceId, k -> new ArrayList<>()).add(p);
        }
        // For limited-port grants we need: grant.id → set<port-id>
        Map<String, Set<String>> portsByGrant = new HashMap<>();
        @SuppressWarnings("unchecked")
        List<Object[]> grantPortRows = em.createNativeQuery(
                        "SELECT grant_id, port_id FROM role_resource_grant_ports")
                .getResultList();
        for (Object[] row : grantPortRows) {
            portsByGrant.computeIfAbsent((String) row[0], k -> new HashSet<>())
                    .add((String) row[1]);
        }

        // Build the accept rules, deduplicating by (peer, resource.ip, transport, port).
        // A user in two roles that both grant the same resource:port produces ONE rule,
        // not two — the kernel doesn't care and a duplicate comment is noisy.
        Map<String, String> rulesByKey = new LinkedHashMap<>();
        // Track (peer.assignedIp, resource.ip) pairs that have at least one grant —
        // used below to emit implicit ICMP accept rules (ping reachability check).
        Set<String> icmpPairs = new HashSet<>();
        for (Peer peer : peers) {
            List<String> userRoles = rolesByUser.getOrDefault(peer.userId, List.of());
            if (userRoles.isEmpty()) continue;
            for (String roleId : userRoles) {
                Role role = roleById.get(roleId);
                if (role == null) continue;
                for (RoleResourceGrant g : grantsByRole.getOrDefault(roleId, List.of())) {
                    Resource res = resourceById.get(g.resourceId);
                    if (res == null) continue;
                    List<ResourcePort> resPorts = portsByResource.getOrDefault(res.id, List.of());
                    if (resPorts.isEmpty()) continue;
                    List<ResourcePort> grantedPorts = g.allPorts
                            ? resPorts
                            : resPorts.stream()
                                    .filter(rp -> portsByGrant.getOrDefault(g.id, Set.of()).contains(rp.id))
                                    .toList();
                    for (ResourcePort rp : grantedPorts) {
                        String comment = String.format(
                                "islandr:role=%s peer=%s user=%s resource=%s %s%s",
                                escape(role.name),
                                escape(peer.name),
                                escape(userName.getOrDefault(peer.userId, "?")),
                                escape(res.name),
                                escape(rp.protocol),
                                rp.label == null || rp.label.isBlank() ? "" : " " + escape(rp.label));
                        for (String[] td : expandTransport(rp)) {
                            String effectiveTransport = td[0];
                            String dportClause = td[1];
                            String key = peer.assignedIp + "|" + res.ip + "|"
                                    + effectiveTransport + "|" + rp.port + "|"
                                    + (rp.portEnd == null ? "" : rp.portEnd);
                            if (rulesByKey.containsKey(key)) continue;
                            String rule = dportClause.isEmpty()
                                    ? String.format(
                                            "    iifname \"%s\" ip saddr %s ip daddr %s %s accept comment \"%s\"",
                                            wgInterface, peer.assignedIp, res.ip, effectiveTransport, comment)
                                    : String.format(
                                            "    iifname \"%s\" ip saddr %s ip daddr %s %s %s accept comment \"%s\"",
                                            wgInterface, peer.assignedIp, res.ip, effectiveTransport, dportClause, comment);
                            rulesByKey.put(key, rule);
                        }
                        // Mark this (peer, resource) pair for implicit ICMP allow
                        icmpPairs.add(peer.assignedIp + "|" + res.ip + "|" + escape(peer.name) + "|" + escape(res.name));
                    }
                }
            }
        }
        // Implicit ICMP (ping) accept for every (peer, resource) pair that has at least
        // one port grant. This lets users verify connectivity without opening extra rules.
        for (String pair : icmpPairs) {
            String[] parts = pair.split("\\|", 4);
            String peerIp = parts[0], resIp = parts[1], peerName = parts[2], resName = parts[3];
            String icmpKey = peerIp + "|" + resIp + "|icmp";
            if (rulesByKey.containsKey(icmpKey)) continue;
            String rule = String.format(
                    "    iifname \"%s\" ip saddr %s ip daddr %s icmp type echo-request accept comment \"%s\"",
                    wgInterface, peerIp, resIp,
                    "islandr:peer=" + peerName + " resource=" + resName + " ping");
            rulesByKey.put(icmpKey, rule);
        }

        StringBuilder sb = new StringBuilder(BANNER.length() + 256 + 96 * rulesByKey.size());
        sb.append(BANNER).append('\n');
        // "add table" is idempotent — it creates the table when missing (cold
        // start) and is a no-op when it already exists. The subsequent
        // "flush table" then safely empties it before rewriting the rules.
        // Without this, nft errors on first boot: "Could not process rule:
        // No such file or directory (table islandr does not exist)".
        sb.append("add table inet islandr\n");
        sb.append("flush table inet islandr\n");
        sb.append("table inet islandr {\n");
        sb.append("  chain forward {\n");
        // priority -1 so our default-deny hits BEFORE UFW's forward chain
        // (which sits at priority 0). On a UFW-free hub this is harmless;
        // on a UFW-managed Ubuntu it makes the ordering deterministic.
        sb.append("    type filter hook forward priority -1; policy drop;\n");
        sb.append('\n');
        sb.append("    ct state established,related accept comment \"islandr:conntrack return traffic\"\n");
        sb.append("    ct state invalid drop comment \"islandr:conntrack invalid\"\n");
        if (!rulesByKey.isEmpty()) {
            sb.append('\n');
            for (String rule : rulesByKey.values()) {
                sb.append(rule).append('\n');
            }
        }
        sb.append("  }\n");
        sb.append("}\n");

        return new Snapshot(sb.toString(), rulesByKey.size());
    }

    /** Empty-state ruleset: no peers, no rules — but the table still exists. */
    private String emptyTable() {
        return BANNER + "\n"
                + "add table inet islandr\n"
                + "flush table inet islandr\n"
                + "table inet islandr {\n"
                + "  chain forward {\n"
                + "    type filter hook forward priority -1; policy drop;\n"
                + "\n"
                + "    ct state established,related accept comment \"islandr:conntrack return traffic\"\n"
                + "    ct state invalid drop comment \"islandr:conntrack invalid\"\n"
                + "  }\n"
                + "}\n";
    }

    /**
     * Expands one ResourcePort into (effectiveTransport, dportClause) pairs.
     * "both" yields two pairs (tcp + udp). port=0 yields an empty dportClause.
     * Returns a list of String[2]: [transport, dportClause].
     */
    private static List<String[]> expandTransport(ResourcePort rp) {
        String dport;
        if (rp.port == 0) {
            dport = "";
        } else if (rp.portEnd != null) {
            dport = "dport " + rp.port + "-" + rp.portEnd;
        } else {
            dport = "dport " + rp.port;
        }
        if ("both".equals(rp.transport)) {
            return java.util.Arrays.asList(new String[]{"tcp", dport}, new String[]{"udp", dport});
        }
        return java.util.Collections.singletonList(new String[]{rp.transport, dport});
    }

    /** Quotes that would break nft's string parser get stripped from comments. */
    private static String escape(String s) {
        if (s == null) return "";
        return s.replace("\"", "").replace("\\", "").replace("\n", " ");
    }

    /** Combined output of a single build: the ruleset text and how many rules it contains. */
    public record Snapshot(String rulesetText, int ruleCount) {}
}
